### ISSUE TITLE
Decide which methodology for getting version info is correct

### ISSUE THREAD

**Issue by drewoldag** [lincc-frameworks/python-project-template#110]
When gathering the `release` information in conf.py for Sphinx we use two approaches. 

In the template to be hydrated we use this: https://github.com/lincc-frameworks/python-project-template/blob/main/python-project-template/docs/conf.py.jinja#L22

```
from importlib.metadata import version
release = version("{{package_name}}")
```

In the documentation for the python-project-template we use this: https://github.com/lincc-frameworks/python-project-template/blob/main/docs/conf.py#L15

```
from setuptools_scm import get_version
release = get_version(root="..")
```

I think that both work, however, the second version requires installing `setuptools_scm` explicitly in the dependencies list in the pyproject.toml file, whereas the first version doesn't require an additional dependency. 

I'm not sure if one is more correct than the other, but seems like something we can consolidate on. 

@delucchi-cmu do you have a strong opinion one way or the other?

**Comment by delucchi-cmu** [comment]
I agree that it's not great to have two different approaches. However. =]

The first option won't work *in the case of the python project template* because it isn't a true python package.

Since we can't really use the first option (but other projects maybe should) we could add a note to the conf.py saying why we have to do it that way (and why it's different from what we suggest for other projects).

**Comment by drewoldag** [comment]
OK, I see what you're saying @delucchi-cmu. Given all that, I don't think that this is a priority right now, so I'm comfortable closing this as "not planned"
