### ISSUE TITLE
pytest fails on newly hydrated project

### ISSUE THREAD

**Issue by cchris28** [lincc-frameworks/python-project-template#114]
python -m pytest --cov=./src --cov-report=html && echo pass || echo fail

control.py:858: CoverageWarning: No data was collected. (no-data-collected)
  self._warn("No data was collected.", slug="no-data-collected")

The answer file:

# Changes here will be overwritten by Copier
_commit: v1.2.1-73-g04ce855
_src_path: /Users/cchris28/projects/python-project-template
author_email: cchris28@uw.edu
author_name: Carl Christofferson
create_example_module: false
custom_install: true
include_notebooks: false
module_name: mymodule
preferred_linter: pylint
project_license: MIT
project_name: myproject
use_gitlfs: disabled
use_isort: true

**Comment by drewoldag** [comment]
Were you running this manually or via precommit?

**Comment by drewoldag** [comment]
Either way, seems related to #95

**Comment by cchris28** [comment]
Related in the same way it is related to #111. They are failures of build/commit on permutations of answers.
It is a follow on to #95 since it is a link in a chain. I suppose we could reopen #95.

I ran with both with precommit (where I first noticed) and  manually (command above).
This could get fairly difficult to exhaustively test.

**Comment by drewoldag** [comment]
I don't see an immediately obvious way to fix this. 

If we conditionally exclude part of the pre-commit command when the user selects 'no example modules", then there's not an easy way for that user to get the pytest-cov bit back for the pre-commit when they actually have tests. 

And there doesn't appear to be any flags or settings that would allow pytest-cov to ignore warnings, and subsequently _not_ cause the pre-commit to fail. 

Another option, that would drastically simplify the overall logic would be to remove the option to exclude example modules, and instead always include them.

**Comment by drewoldag** [comment]
Yet another option would be to just remove the code coverage per from the precommit hook. It's hard to say how useful that part really is. 

Perhaps some people would look at it while committing? Seems more likely that if they were paying attention to coverage, they would look prior to committing.

**Comment by drewoldag** [comment]
pytest has a flag that can be passed to only collect tests, and not run anything. So a possible solution might involve something like:

`python -m pytest --collect-only -qq && python -m pytest --cov=./src --cov-report=html || echo $?`

Meaning if there are tests collected, run the tests. Otherwise, print out the exit code of the collection process (which itself should return an exit code of 0 and allow pre-commit to pass)

However, when I try to run this I get the following output from pre-commit: `ERROR: file or directory not found: &&`.

I've tried grouping the commands like this: `(python...) && (python...) || echo $?` but that produces this error: `Executable `(python` not found`.
