### ISSUE TITLE
Investigate options for on-premise github actions

### ISSUE THREAD

**Issue by drewoldag** [lincc-frameworks/python-project-template#126]
GitHub has a feature that allows actions to be run on user-provided hardware. This is important for packages like KBMOD that require GPUs for testing since GitHub doesn't provide that hardware for actions. 

This may be more broadly applicable to other use cases, and we should consider how/if we would want to support this in the python project template. 

First order options include:
1. Add documentation about how to do this, but don't actually implement anything. And determine if that documentation belongs with the python project template documentation, or somewhere more discoverable. 
2. Include some support for this in the python project template
3. Create a new template to support this, and leverage the composability of Copier to allow users to take either or both templates to start or update their projects.

@cchris28 and @delucchi-cmu if you have additional thoughts on this, please feel free to add them to this issue :)

**Comment by cchris28** [comment]
github refers to these as "self-hosted"

Worth noting that github recommends this feature be restricted to private repositories since it might be possible to break out of the CI and execute arbitrary commands.

https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners#self-hosted-runner-security

**Comment by cchris28** [comment]
We decided this is too involved to easily inlcude in the template. The security concerns alone require special consideration.
