### ISSUE TITLE
Add option for running git init or not

### ISSUE THREAD

**Issue by smcguire-cmu** [lincc-frameworks/python-project-template#140]
Currently at the end of the copier run, git init is run. This could be changed to be an option to run or not in the custom options in case someone doesn't want to use git.

**Comment by drewoldag** [comment]
In order to avoid extra questions during the configuration stage, we've decided to continue to run git init by default. Git init is considered a very common use case, and if we provided the option to exclude it, then we would likely need to introduce a fair amount of new logic so that we don't render things like the github workflows etc...

Instead we'll implement a slightly more substantial bash command that will attempt to initialize the new directory as a git repo, and report a pass/fail depending on the results. This is tracked in issue #193
