### ISSUE TITLE
Potential duplicate stage in asv workflow

### ISSUE THREAD

**Issue by delucchi-cmu** [lincc-frameworks/python-project-template#259]
@OliviaLynn  pointed out in review of https://github.com/astronomy-commons/hipscat/pull/124 that the asv-pr and asv-main scripts have two stages with action like: `Cache Python ${{ env.PYTHON_VERSION }}`

Is this duplication intentional and necessary?

**Comment by camposandro** [comment]
Great point @OliviaLynn @delucchi-cmu! 

The duplication of this cache action is only required because each job defined in the workflow runs in a fresh (isolated) environment. The first job "setup-python" is responsible for installing Python and caching the environment so that posterior jobs may pick it up and reuse it. At the moment we only have a job succeeding this "setup-python" so we could actually simplify the workflow, use a single job and remove such duplication of caching calls.

**Comment by drewoldag** [comment]
@camposandro would you recommend that we simplify the workflow, or leave as is to make future additions easier? If you recommend, leave as is, feel free to close out this issue :)

**Comment by camposandro** [comment]
These cache stages have been removed in https://github.com/lincc-frameworks/python-project-template/pull/482.
