### ISSUE TITLE
README file in the `.github` directory

### ISSUE THREAD

**Issue by dougbrn** [lincc-frameworks/python-project-template#491]
Github repositories [look first at the `.github` folder](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes#about-readmes) for README files to display on the repository home page. Currently, the PPT includes a readme file within that directory which explains the contents of the folder, this will override the repo-level readme when viewing the repository on github:

![Screen Shot 2024-10-14 at 9 29 12 AM](https://github.com/user-attachments/assets/3051b74f-0588-4f4b-9700-9d79ae28857a)

I would recommend we rename this file to something other than README

**Comment by drewoldag** [comment]
So it turns out this is expected, and even documented here: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes#about-readmes

Though it isn't the behavior that we want, so we'll just need to move the READMEs to the appropriate subfolders.
