### ISSUE TITLE
Think more about author for team projects

### ISSUE THREAD

**Issue by delucchi-cmu** [lincc-frameworks/python-project-template#55]
Should the author of our libraries be the individuals, or LINCC-Frameworks?

**Comment by drewoldag** [comment]
Yeah, this is a good open question. A related question that @dougbrn mentioned was, "who should be the owner of projects that we publish to PyPI?"

**Comment by dougbrn** [comment]
Astropy has a potential model to follow on the PyPI (and perhaps by extension the template) end: https://pypi.org/project/astropy/ 

The ability to add maintainers helps users connect to the right team members, without needing to attribute the whole development credit to them. There doesn't appear to be a standard though, just from poking around other large packages (scipy, numpy, etc.)

**Comment by drewoldag** [comment]
Tagging @jeremykubica on this issue. I asked him about this, and he's going to check with Rachel and Andy to get their input. 

Also, we might want to pop this issue out of the python-project-template repo, and move it to the LINCC-frameworks project tracker as an issue not directly related to one repository. No rush on that though, since this seems like it might be the repository most closely related to this topic anyway 😄

**Comment by jeremykubica** [comment]
For the team projects, it should be "LINCC Frameworks Team" although the template should be flexible to support teams outside our own.
