### ISSUE TITLE
README.md has dangling reference to .github/workflows/python-package.yml

### ISSUE THREAD

**Issue by cchris28** [lincc-frameworks/python-project-template#94]
The reference to python-package.yml seems to be stale as there is no such file .github/workflows/python-package.yml in the hydrated project.

## GitHub CI is ready out of the box

Notice that this template contains a `.github/workflows` directory with a `python-package.yml` file. Because of this, any project created from this template that uses GitHub as a repository will automatically have CI enabled.

GitHub workflows are extremely useful, for more information, check out the [About workflows](https://docs.github.com/en/actions/using-workflows/about-workflows) page.

**Comment by drewoldag** [comment]
I think that this ticket is out of date at this point. This PR #84 removed a large portion of the README so that we can avoid keeping two sources of documentation in sync. The documentation on readthedocs [(here)](https://lincc-ppt.readthedocs.io/en/latest/practices/ci_testing.html#how-to-manage) is correct.
